---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: TRMNL Screenshot"
  org.opencontainers.image.description: "Capture Home Assistant dashboards for TRMNL e-ink devices"
  org.opencontainers.image.source: "https://github.com/chbarnhouse/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
